### PR TITLE
projet ready for pull : support for french

### PR DESCRIPTION
**Pull request by Pantalaymon**
Finally support for french is completed !

List of the added features : 

- added /fr/ directory in /coreferee/lang/
   - language_specific_rules.py
   - config.cfg
   - data files
   - Licence file citing the ressources used
- added /fr/ directory in /tests/ 
   - test_rules_fr.py
   - test_smoke_tests.py
- added DEMOCRATConllLoader class in coreferee/training/loaders.py
- added /fr/ directory in models : contains the trained models

I'll the zip file of the training by mail.

### CODE REVIEW

**Comment by richardpaulhudson** [comment]
Hi @Pantalaymon , thank you very much - having written Coreferee to be extensible for further languages, it's great to see somebody has taken the time to use the feature and been successful. It must have been a great deal of work!

One slightly complicated thing is that I am now working for Explosion, the creators of spaCy, where we are also working on a coref solution that is fully integrated into spaCy, starting with English. Until we have worked out a clear way of letting users know when to use the native solution (probably to start with for English) and when to use Coreferee (probably to start with for the other three languages) I'm still maintaining Coreferee here, but at some point in the not too distant future I will be maintaining it under github.com/explosion as well. To that end, would it please be possible for you to sign the spaCy Contributor Agreement (https://github.com/explosion/spaCy/blob/master/.github/CONTRIBUTOR_AGREEMENT.md), following the instructions there but for the time being creating a pull request without anything but the agreement; perhaps you could also note that you are submitting for Coreferee in case somebody other than me processes the pull request.

A few things I noticed looking and trying out the code:

- Three tests are failing at my end: `test_potential_referreds_over_maximum_sentence_referential_distance` from the rules test and `test_documentation_example_2` and `test_entity_coreference` from the smoke tests. Are these failing for you as well if you redeploy in a new virtual environment?
- You mention a source of first names, but the pull request contains no changes to the male and female names files except that 'José' (which is incidentally my son's name :-)) has been deleted from the male names. Is this what you intended? I would have expected some French first names to be added to each file.
- Within the file `person_roles.dat` there is an entry `dame` at the point in the alphabet where I would expect the entry `homme` — is this right?

It would be great if you could have another look at these points, and send me the training .zip file.

Thanks again and best wishes, Richard

**Comment by Pantalaymon** [comment]
Thanks  for your feedback !
Indeed there was an issue with my creation of the new first name files, this is fixed now.
The file `person_roles.dat ` and all the other `.dat` files in have been cleaned up with their content sorted in alphabetical order.
I had forgotten to update the test files after retraining the model, this is done now.

This is great to hear that Explosion plans to add coreference resolution and even information extraction in the base spacy pipeline ! I bet many companies and academics will be delighted once it's available. 

Will some of the great work you've done with coreferee transfer to this new project as well? And is there some place where we can follow the advancement of the project (I suppose the details of the implementation are confidential until release) ?
Anyways, when you plan to add support for other languages in the future, I would be glad to collaborate in the project if needed for french.

I will sign the agreement as soon as I have time to read through it all 💯

**Comment by Pantalaymon** [comment]
Thanks  for your feedback !
Indeed there was an issue with my creation of the new first name files, this is fixed now.
The file `person_roles.dat ` and all the other `.dat` files in have been cleaned up with their content sorted in alphabetical order.
I had forgotten to update the test files after retraining the model, this is done now.

This is great to hear that Explosion plans to add coreference resolution and even information extraction in the base spacy pipeline ! I bet many companies and academics will be delighted once it's available. 

Will some of the great work you've done with coreferee transfer to this new project as well? And is there some place where we can follow the advancement of the project (I suppose the details of the implementation are confidential until release) ?
Anyways, when you plan to add support for other languages in the future, I would be glad to collaborate in the project if needed for french.

I sent you the zip file at your (what I guess is former) msg mail address. Perhaps There is another address I should send it to?

I will sign the agreement as soon as I have time to read through it all 💯

**Comment by richardpaulhudson** [comment]
Hi @Pantalaymon, thanks for the update, everything looks good and all the tests are passing now. Unfortunately my old msg address is no longer active, but you can reach me at richard@explosion.ai. If you could submit the agreement to Explosion and send me the zip file, I'll include the pull request and put together a new release. Thank you again for your excellent and valuable contribution! 💯

**Comment by Pantalaymon** [comment]
Hello, 

I just signed and submitted the agreement.
I also pushed the files with modification marks on the files I modified
I sent a mail with the zip file to your new address.

**Comment by richardpaulhudson** [comment]
Where did you submit the agreement to - I can't see it?

**Comment by Pantalaymon** [comment]
I may have overlooked a step . Is this good [now](https://github.com/explosion/spaCy/pull/9737) ?

**Pull request merged**
